// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJlKRznHYmQluZBuGVGgUr7YS50909rhg',
    appId: '1:429595489316:web:546cc6c7d4593a9a4694b1',
    messagingSenderId: '429595489316',
    projectId: 'foodapp-c31fa',
    authDomain: 'foodapp-c31fa.firebaseapp.com',
    storageBucket: 'foodapp-c31fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKbNE24I2t1D1fGf6MrFTQoGX1asnuZGU',
    appId: '1:429595489316:android:ad8d35cb3edca7ae4694b1',
    messagingSenderId: '429595489316',
    projectId: 'foodapp-c31fa',
    storageBucket: 'foodapp-c31fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8vSespnFXq5eUkTkZJxs48mQm87BbkEE',
    appId: '1:429595489316:ios:fafa38d5f03f3f004694b1',
    messagingSenderId: '429595489316',
    projectId: 'foodapp-c31fa',
    storageBucket: 'foodapp-c31fa.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );
}
